- alias: "TV is OFF"
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      from: "on"
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: time
        after: "20:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal

- alias: "TV is ON"
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: "on"
      from: "off"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: time
        after: "20:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_dim

- alias: "Turn night sound in the evening"
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      from: "off"
      to: "on"
  condition:
    condition: time
    after: "20:00:00"
  action:
    - service: sonos.set_option
      entity_id: media_player.salon
      data:
        night_sound: yes
    - service: media_player.volume_set
      entity_id: media_player.salon
      data:
        volume_level: 0.14

- alias: "Turn off night sound before the evening"
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      from: "off"
      to: "on"
  condition:
    condition: time
    before: "20:00:00"
  action:
    service: sonos.set_option
    entity_id: media_player.salon
    data:
      night_sound: no
