# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

steps:
- script: |
    pip install --upgrade pip
    pip install homeassistant
  displayName: 'Install pip and latest home assistant'

- script: |
    mv travis_secrets.yaml secrets.yaml
    hass -c . --script check_config
  displayName: 'Validate Configuration' 
