trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: homeassistant/home-assistant:latest

steps:
- script: |
    mv travis_secrets.yaml secrets.yaml
    hass -c . --script check_config
  displayName: 'Validate Configuration' 
