- platform: synologydsm
  host: 192.168.100.5
  username: !secret buffalo_username
  password: !secret buffalo_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - disk_status
    - volume_percentage_used
